[MYVARS]
RELAYCOM=COM220
BMCCOM=COM230
BIOSCOM=COM240

PUTTY_PATH=C:\Program Files\PuTTY\putty.exe
PUTTY_LOGS_PATH=C:\Temp\PuttyLogs

BMC_IP=10.98.66.127
BMC_USER=root
BMC_PASS=0penBmc1

#Define with Raritan_FQDN:PORT
#Example: SUT_AC1=jf53nor09bp0101.deacluster.intel.com:21
SUT_AC1=jf53nor09bp0101.deacluster.intel.com:21
SUT_AC2=jf53nor09bp0101.deacluster.intel.com:22

PYTHON_PATH=C:\Python311
PYTHONSV_PATH=C:\pythonsv\diamondrapids\startdmr.py