[MYVARS]
RELAYCOM=COM220
BMCCOM=COM230
BIOSCOM=COM240

PUTTY_PATH=C:\Program Files\PuTTY\putty.exe
PUTTY_LOGS_PATH=C:\Temp\PuttyLogs

BMC_IP=cs16ca101gb0501.deacluster.intel.com
BMC_USER=root
BMC_PASS=0penBmc1

PDU_USER=EMR-PVST
PDU_PASS=P@ssword1234!234

# Define with Raritan_FQDN:PORT
# Example: SUT_AC1=jf53nor09bp0901.deacluster.intel.com:21
# SUT_AC5 should be the Aggregator
SUT_AC1=cs16ca101gp0501.deacluster.intel.com:35
SUT_AC2=cs16ca101gp0501.deacluster.intel.com:36
SUT_AC3=cs16ca101gp0501.deacluster.intel.com:25
SUT_AC4=cs16ca101gp0501.deacluster.intel.com:26
SUT_AC5=cs16ca101gp0501.deacluster.intel.com:27

PYTHON_PATH=C:\Python311
PYTHONSV_PATH=C:\pythonsv\diamondrapids\startdmr.py